import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { cities, services, priorityPages, references } from '../data/seo-pages.mjs';

const site = 'https://gala-pincus.de';
const esc = (v) => String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const slug = (service, city) => `${service}-${city}`;
const refFor = (service) => references[service] || 'René Pincus Baum- und Landschaftspflege in der Region';

function schema(service, city, url) {
  return JSON.stringify({ '@context':'https://schema.org', '@type':'Service', name:`${services[service].name} in ${cities[city].name}`, serviceType:services[service].name, areaServed:{'@type':'City',name:cities[city].name}, provider:{'@type':'LocalBusiness',name:'René Pincus Baum- & Landschaftspflege', url:site}, url });
}

function page(service, city) {
  const s = services[service], c = cities[city], path = `/${slug(service, city)}/`, url = `${site}${path}`;
  return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(s.name)} in ${esc(c.name)} | René Pincus</title><meta name="description" content="${esc(s.name)} in ${esc(c.name)}: persönliche Beratung, Planung und Umsetzung durch René Pincus. Kostenlos und unverbindlich anfragen."><link rel="canonical" href="${url}"><script type="application/ld+json">${schema(service,city,url)}</script><link rel="stylesheet" href="/styles.css"></head><body>
<header class="site-header"><a class="brand" href="/">René Pincus</a><a class="header-cta" href="#anfrage">Projekt anfragen</a></header>
<main><section class="hero"><p class="eyebrow">Garten- und Landschaftspflege · ${esc(c.name)}</p><h1>${esc(s.name)} in ${esc(c.name)}</h1><p class="lead">${esc(s.intent)} – mit persönlicher Beratung, sauberer Planung und Umsetzung aus einer Hand.</p><a class="button" href="#anfrage">Kostenlose Anfrage stellen</a></section>
<section class="content"><h2>${esc(s.name)} für Privat- und Gewerbekunden</h2><p>René Pincus realisiert Außenanlagen und Pflegearbeiten in ${esc(c.name)} und der Region. Vor Beginn werden Grundstück, Zugänglichkeit, Material, Umfang und gewünschter Zeitraum gemeinsam betrachtet.</p><div class="grid"><article><h3>Persönliche Beratung</h3><p>Ihre Anforderungen und die Gegebenheiten vor Ort stehen am Anfang des Projekts.</p></article><article><h3>Planung &amp; Festpreis</h3><p>Leistungsumfang und Material werden nachvollziehbar abgestimmt.</p></article><article><h3>Eigener Fuhrpark</h3><p>Modernes Fachgerät unterstützt eine effiziente und saubere Ausführung.</p></article></div></section>
<section class="content"><h2>Passendes Pincus-Projekt</h2><p>${esc(refFor(service))}. Weitere Arbeiten können je nach Vorhaben kombiniert werden – etwa Gartengestaltung, Pflege, Pflasterung, Terrasse, Zaun, Baumarbeiten, Erdarbeiten oder Entwässerung.</p></section>
<section class="content"><h2>So läuft die Anfrage ab</h2><ol><li>Projekt kurz beschreiben und Kontaktdaten senden.</li><li>Rückmeldung und Abstimmung der nächsten Schritte.</li><li>Bei Bedarf Besichtigung vor Ort.</li><li>Planung, Angebot und anschließende Ausführung.</li></ol></section>
<section id="anfrage" class="lead-section"><div><p class="eyebrow">Kostenlos &amp; unverbindlich</p><h2>Ihr Projekt in ${esc(c.name)}</h2><p>Schildern Sie kurz Ihr Vorhaben. Fotos können direkt mitgesendet werden.</p></div><form id="lead-form"><input name="contact_name" required placeholder="Name"><input name="phone" placeholder="Telefon"><input name="email" type="email" placeholder="E-Mail"><input name="postcode" placeholder="PLZ"><input name="city" value="${esc(c.name)}" placeholder="Ort"><input type="hidden" name="service" value="${esc(s.name)}"><select name="project_size"><option value="">Projektgröße</option><option>unter 50 m²</option><option>50–100 m²</option><option>100–250 m²</option><option>250–500 m²</option><option>über 500 m²</option></select><select name="desired_period"><option value="">Zeitraum</option><option>sofort</option><option>1–3 Monate</option><option>3–6 Monate</option><option>später</option></select><textarea name="description" rows="5" placeholder="Was soll gemacht werden?"></textarea><label>Projektfotos <input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label class="consent"><input type="checkbox" required> Ich stimme der Verarbeitung meiner Angaben zur Bearbeitung meiner Anfrage zu.</label><button class="button" type="submit">Anfrage absenden</button><p id="form-status" class="form-status" role="status"></p></form></section>
<section class="content"><h2>Häufige Fragen</h2><details><summary>Was kostet ${esc(s.name)} in ${esc(c.name)}?</summary><p>Das hängt von Umfang, Fläche, Material, Zugänglichkeit und gewünschtem Ergebnis ab. Ein konkretes Angebot wird auf Basis Ihrer Angaben und bei Bedarf nach einer Besichtigung erstellt.</p></details><details><summary>Kann ich weitere Arbeiten kombinieren?</summary><p>Ja. Mehrere Arbeiten rund um Garten und Außenanlagen können zu einem abgestimmten Projekt verbunden werden.</p></details><details><summary>Kann ich Fotos mitsenden?</summary><p>Ja. Fotos helfen bei der ersten Einschätzung des Vorhabens.</p></details></section></main><footer><p>René Pincus Baum- &amp; Landschaftspflege · Wasserkurlerstr. 33 · 59174 Kamen</p><p>Kamen · Unna · Dortmund · Bergkamen · Schwerte · Hamm · Lünen · Iserlohn</p><p><a href="/impressum/">Impressum</a> · <a href="/datenschutz/">Datenschutz</a></p></footer><script src="/lead-form.js" defer></script></body></html>`;
}

const urls = [site + '/'];
for (const [service, city] of priorityPages) { const path = `/${slug(service,city)}/`; await mkdir(join(process.cwd(), slug(service,city)), {recursive:true}); await writeFile(join(process.cwd(), slug(service,city), 'index.html'), page(service,city)); urls.push(site + path); }
await writeFile(join(process.cwd(),'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);
await writeFile(join(process.cwd(),'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${site}/sitemap.xml\n`);
console.log(`Generated ${priorityPages.length} priority landing pages.`);
